### ISSUE TITLE
In an infinite loop the first element is replaced by a empty string and never seen again

### ISSUE THREAD

**Issue by AngeloGiuseppe** [hosein2398/Textra#2]
In an infinite loop the first element is replaced by a empty string and never seen again, so the first element its not seen again after the first loop

words: ['show', 'palnet', 'fail', 'sample text', 'testangelodata']

textra :data='words' :timer="1.1" :infinite='true' filter="left-right"

video: https://vimeo.com/259125161

btw loved your plugin , its the unique one it works , keep the good work 👍 !!

**Comment by hosein2398** [comment]
Hey,
Thanks you for bug report.
I'll fix it ASAP
