### ISSUE TITLE
Does not work on nuxt

### ISSUE THREAD

**Issue by WisdomEye** [hosein2398/Textra#7]
Trying use it on nuxt I am getting the error:

`render function or template not defined in component: textra`

Test made with the example of instructions.

**Comment by hosein2398** [comment]
Hey,
I'll release a new version soon I'll try to fix this too.

**Comment by hosein2398** [comment]
Have you tried this with `ssr: false` ?

**Comment by hosein2398** [comment]
This just work with that option,in your Nuxt config:
```
plugins: [{
  src: '~/plugins/textra',
  ssr:false
}]
```

**Comment by WisdomEye** [comment]
> textra

Thanks for the reply!!

Yes, have tried that, but, now I did an new test using the new recomendation from docs:

```javascript
plugins: [
	{ src: '~/plugins/textra.js', mode: 'client' }
],

Its working, the only issue I have noticed is a lot of errors on console now, like:

`error [Vue warn]: The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`

Or

`warn Mismatching childNodes vs. VNodes:  NodeList(5) [h1.heading, text, div.textra, text, p.caption] (5) [VNode, VNode, VNode, VNode, VNode]`

Note on this Nuxt I am using Vuetify, not sure if there some incompatibility.

**Comment by WisdomEye** [comment]
Quick note about using the plugin on Nuxt, the file textra.js inside /plugins:
```javascript
import Vue from 'vue';
import {Textra} from 'vue-textra';

Vue.use(Textra);
```

Removed:

```javascript
import App from './App.vue';

new Vue({
	el: '#app',
	render: h => h(App)
});

To use it with Nuxt.

**Comment by hosein2398** [comment]
Here is the answer:
https://github.com/nuxt/nuxt.js/issues/1700

**Comment by WisdomEye** [comment]
> Here is the answer:
> [nuxt/nuxt.js#1700](https://github.com/nuxt/nuxt.js/issues/1700)

Thank you so much for the patience and support!!!

Its working as desired and without errors on browser console now.

Just an quick note (maybe you should update the readme with this info).

For outdate nuxt (at least before version 2.9.2) the following code should works:

nuxt.config.js
```javascript
plugins: [{
  src: '~/plugins/textra',
  ssr:false
}]
```

And on component:

```javascript
	<no-ssr>
		<textra :data='words' :timer="1.1" filter="flash" />
	</no-ssr>
```

For current nuxt (2.9.2) and probaly next ones, need use:

nuxt.config.js
```javascript
plugins: [{
  src: '~/plugins/textra',
  mode: 'client'
}]
```

Component
```javascript
	<client-only>
		<textra :data='words' :timer="1.1" filter="flash" />
	</client-only>
```

Once more time, thank you very much!!!
